[graph]
all-features = true

[advisories]
unmaintained = "workspace"
unsound = "all"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[bans.std-replacements]
scope = "workspace"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93
unused-allowed-license = "allow"
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
